[webservers]

192.168.1.100 ansible_user=adminuser ansible_port=22

[webservers:vars]

ansible_become=yes
ansible_become_method=sudo

[dbservers]

192.168.1.101 ansible_user=adminuser ansible_port=22

[all:vars]

ansible_ssh_private_key_file=/home/adminuser/.ssh/id_rsa

ansible_ssh_common_args='-o StrictHostKeyChecking=yes'